### ISSUE TITLE
如果需要在第一行新插入一行代码，后面的Ax、Bx是自动调整，还是得全部手动改一遍？

### ISSUE THREAD

**Issue by deepzliu** [SPLWare/esProc#17]
请教个问题，RT，谢谢~

**Comment by wunanraq** [comment]
插入行列后会自动调整单元格引用。

**Comment by deepzliu** [comment]
> 插入行列后会自动调整单元格引用。

好的，谢谢！还有个小疑问，如果能复用代码，然后复制粘贴大量代码呢？

**Comment by wunanraq** [comment]
复用代码，不建议复制粘贴多次。
可以使用“子程序调用”（func）或者“跨网格调用”（call）。
在教程里有详细说明。
