### ISSUE TITLE
IDE能否增加运行时间输出

### ISSUE THREAD

**Issue by zoomafia** [SPLWare/esProc#18]
运行脚本的时候能否自动输出脚本运行时间，而不用每次都手动写。比如默认输出整个脚本的运行时间，如果执行某个格子或执行到光标则输出当前执行时间；如果能把每个格子的运行时间都显示出来不知道是不是会更好。更进一步，jar包集成或服务端日志也能输出运行时间

**Comment by wunanraq** [comment]
调试执行时，在IDE右侧显示值的面板下部，会显示当前格子的计算用时。（这个功能已经有了）
现在新增加了，在IDE中执行SPL完成时，输出SPL计算总用时。

**Comment by zoomafia** [comment]
十分感谢~

> 调试执行时，在IDE右侧显示值的面板下部，会显示当前格子的计算用时。（这个功能已经有了） 现在新增加了，在IDE中执行SPL完成时，输出SPL计算总用时。
