### ISSUE TITLE
SPL建议增加proxy功能

### ISSUE THREAD

**Issue by xiaobai721** [SPLWare/esProc#48]
1、集算器客户端增加网络代理设置，对于一些公司内网来说更友好一些
2、服务器post参数时增加proxy代理选项，感觉这个功能还是很常用的，一般服务器都不会直接连互联网
=httpfile("http://IP:host/scada/v1/uaes/datapoint/history/rawvalue/rtdb/access","{\"nodeIds\":[\"ns=102;s=AI_002_0600.PV\"], \"startTime\":\"2018/6/28 13:10:00\", \"endTime\":\"2018/6/28 13:11:0\", \"returnBounds\":\"false\", \"maxSizePerNode\":\"10\"}"; "Content-Type":"application/json")

**Comment by jbx1279** [comment]
弱弱地问一下：proxy不是应该被底层网络透明掉吗？还需要在应用层处理吗。
这些我们不太熟悉，还不太清楚如何自己搭一个代理来做实验。
另外，这些源代码都是公开的，如果必要也可以自己增加，这件事仅和网络本身有关，与计算无关，不用理解SPL内部逻辑，写个Java的静态函数来设置/清除代理就可以了。

**Comment by xuzaoya** [comment]
jvm属性支持http代理
-Dhttp.proxyHost=代理服务器主机名
-Dhttp.proxyPort=端口号,默认是80
-Dhttps.proxyHost=https代理服务器主机名
-Dhttps.proxyPort=代理端口号,默认是443
-Dhttp.nonProxyHosts=指定绕过代理的主机列表，多个用 | 分割
如果是安装盘，可以在config.txt里配置
如果自己运行主类那直接在java后加上即可

**Comment by xiaobai721** [comment]
> jvm属性支持http代理 -Dhttp.proxyHost=代理服务器主机名 -Dhttp.proxyPort=端口号,默认是80 -Dhttps.proxyHost=https代理服务器主机名 -Dhttps.proxyPort=代理端口号,默认是443 -Dhttp.nonProxyHosts=指定绕过代理的主机列表，多个用 | 分割 如果是安装盘，可以在config.txt里配置 如果自己运行主类那直接在java后加上即可

亲测可以了没问题，感谢呀
