### ISSUE TITLE
数据查询异常

### ISSUE THREAD

**Issue by yanglk2010** [SPLWare/esProc#50]
![image](https://github.com/SPLWare/esProc/assets/14232815/937054c9-c3c4-410c-b62b-f83ce49a4c08)
上图是从mysql数据中获取数据
![image](https://github.com/SPLWare/esProc/assets/14232815/7eeff4e9-ca70-4c4e-a01c-fe88ef112bf7)
数据中明显是有SP显示的，但查询不到数据，select查询tt=="SP"和其他都试过了，也查不到数据

**Comment by xuzaoya** [comment]
写成like(A3.tt,"*SP*")试试

**Comment by RQWangXiaoJun** [comment]
A2格产生了变量tt，标识符是优先解释成变量的，所以select中的tt实际是引用的变量tt的值。
变量名尽量不要跟字段名起重了，如果重了要引用字段可以用~.tt或者A3.tt限定一下。

**Comment by yanglk2010** [comment]
感谢，可以了
> A2格产生了变量tt，标识符是优先解释成变量的，所以select中的tt实际是引用的变量tt的值。 变量名尽量不要跟字段名起重了，如果重了要引用字段可以用~.tt或者A3.tt限定一下。

> ```
> like(A3.tt,"*SP*")
> ```
> 
> 试试
