### ISSUE TITLE
IDE支持自动保存脚本

### ISSUE THREAD

**Issue by zoomafia** [SPLWare/esProc#6]
希望IDE编辑SPL脚本时可以自动保存

**Comment by xuzaoya** [comment]
准备加一选项”自动保存“，不过没有对应文件的网格不能自动保存

**Comment by zoomafia** [comment]
未保存的脚本可以在下次打开IDE的时候默认打开，可以参考notepad++等文本编辑器。新建文本-输入内容（未保存）-关闭编辑器-再打开时默认打开上次未保存的tab。

**Comment by zoomafia** [comment]
![image](https://user-images.githubusercontent.com/89468159/211258777-2e56c03d-43ad-41aa-ada9-d53ec3ccb6ba.png)
感谢增加自动保存，未保存的脚本关闭以后会自动打开，赞了
